name: CI
on: 
  push:
    branches:
      - "main"

jobs:
  Git_Pull:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/udify_mongo/udify-mongo
    steps:
      - name: Run Git stash
        run: git stash
      - name: Taking Git Pull
        run: git pull
      - name: Get Back the .env file
        run: git stash pop

  Creating_docker_Image:
    needs: Git_Pull
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/udify_mongo/udify-mongo
    steps:
      - name: Install dependencies
        run: npm install 


  Deploy_Image:
    needs: Creating_docker_Image
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/udify_mongo/udify-mongo
    steps:
      - name: Deploy the code
        run: pm2 reload 0
